export const vehicleData: Record<string, Record<string, string[]>> = {
  "2-wheeler": {
    "Hero": [
      "Splendor+ XTEC 2.0",
      "Splendor+",
      "Splendor+ XTEC",
      "HF 100",
      "HF Deluxe",
      "Xoom 160",
      "Xoom 125",
      "New Destini 125",
      "Destini Prime",
      "Xoom",
      "Pleasure+ XTEC",
      "Xtreme 125R",
      "Glamour",
      "Super Splendor XTEC",
      "Glamour XTEC",
      "Super Splendor",
      "Xtreme 250R",
      "Xpulse 210",
      "Xtreme 160R 4V",
      "Xtreme 160R",
      "Xpulse 200 4V",
      "Mavrick",
      "Karizma XMR"
    ],
    "Honda": [
      "Shine 100",
      "Hornet 2.0",
      "Livo",
      "Transalp",
      "Shine 125",
      "SP 160",
      "SP 125",
      "Unicorn",
      "NX200",
      "CB300R",
      "Goldwing Tour",
      "CB300F",
      "CB350",
      "CB350 H'ness",
      "CB350RS",
      "NX500",
      "Activa",
      "Dio",
      "CB Shine"
    ],
    "Bajaj": [
      "Bajaj Freedom 125 NG04",
      "Pulsar N125",
      "Pulsar N150",
      "Pulsar N160",
      "Pulsar N250",
      "Pulsar NS400z",
      "Pulsar NS200",
      "Pulsar NS125",
      "Pulsar NS160",
      "Pulsar RS200",
      "Pulsar 125",
      "Pulsar 150",
      "Pulsar 220F",
      "Dominar 250",
      "Dominar 400",
      "Avenger 220 Cruise",
      "Avenger 160 Street",
      "Avenger 220 Street",
      "Platina 100",
      "Platina 110 Drum",
      "CT 110X",
      "Chetak"
    ],
    "TVS": [
      "Apache RR 310",
      "Apache RTR 310",
      "Apache RTR 200 4V",
      "Apache RTR 160 4V",
      "Apache RTR 160",
      "TVS Ronin",
      "TVS Raider",
      "TVS Radeon",
      "TVS Sport",
      "TVS Jupiter",
      "TVS Jupiter 125",
      "TVS NTorq",
      "TVS iQube",
      "TVS X",
      "Star City Plus",
      "Apache"
    ],
    "Yamaha": [
      "R15M",
      "R15 V4",
      "R15S",
      "MT-03",
      "MT-15 Version 2.0",
      "FZ-S Fi Hybrid",
      "FZ-S Fi",
      "FZ-Fi",
      "FZ-S Fi Version 4.0 DLX",
      "FZ-S Fi Version 4.0",
      "FZ-S Fi Version 3.0",
      "FZ-X",
      "R15M MotoGP Edition",
      "MT-15 Version 2.0 MotoGP Edition",
      "Aerox 155",
      "Aerox 155 Version S",
      "RayZR 125 Fi",
      "RayZR 125 Fi Street Rally",
      "Fascino 125 Fi",
      "Fascino"
    ],
    "Suzuki": [
      "Gixxer 155",
      "Gixxer SF 155",
      "Gixxer 250",
      "Gixxer SF 250",
      "V-Strom SX",
      "Katana",
      "Hayabusa",
      "Access 125",
      "Access 125 SE",
      "Burgman Street",
      "Burgman Street EX",
      "Avenis",
      "Access",
      "Intruder"
    ],
    "Royal Enfield": [
      "Hunter 350",
      "Classic 650",
      "Scram 440",
      "Goan Classic 350",
      "Bear 650",
      "Classic 350",
      "Guerrilla 450",
      "Shotgun 650",
      "New Himalayan",
      "Bullet 350",
      "Super Meteor 650",
      "Meteor 350",
      "Interceptor 650",
      "Continental GT 650"
    ],
    "Mahindra": ["Mojo", "Mojo 300"],
    "Vespa": [
      "Vespa",
      "Vespa S",
      "Vespa S Tech",
      "Vespa ZX",
      "Vespa VXL",
      "Vespa Racing Sixties",
      "Vespa Dual",
      "Vespa SXL"
    ],
    "KTM": [
      "KTM 200 Duke",
      "KTM 250 Duke",
      "KTM 390 Duke",
      "KTM RC 200",
      "KTM RC 390",
      "KTM RC GP",
      "KTM 250 Adventure",
      "KTM 390 Adventure",
      "KTM 390 Adventure X",
      "KTM 890 Adventure R",
      "KTM 1290 Super Adventure S",
      "KTM 50 SX",
      "KTM 65 SX",
      "KTM 85 SX",
      "KTM 250 SX-F",
      "KTM 450 SX-F",
      "KTM 350 EXC-F Six Days",
      "KTM 390 Enduro R",
      "Duke 125"
    ],
    "Harley Davidson": [
      "Street Bob",
      "Breakout",
      "Fat Boy",
      "Heritage Classic",
      "Street Glide",
      "Road Glide",
      "CVO Street Glide",
      "CVO Road Glide",
      "Pan America 1250 Special",
      "Nightster",
      "Nightster Special",
      "Sportster S",
      "Street 750",
      "Iron 883",
      "Forty-Eight"
    ],
    "Triumph": [
      "Tiger 1200 Range",
      "Tiger 900 Range",
      "Tiger Sport 660",
      "New Speed T4",
      "New Speed Twin 1200",
      "New Speed Twin 900",
      "Speed 400",
      "Scrambler 400 X",
      "Scrambler 400 XC",
      "Bonneville T100",
      "Scrambler 900",
      "Scrambler 1200",
      "Bonneville T120",
      "Bonneville Bobber",
      "Bonneville SpeedMaster",
      "New Speed Triple 1200 RS",
      "New Trident 660",
      "Street Triple 765",
      "Speed Triple 1200 RS",
      "Rocket 3 Storm",
      "Daytona 660",
      "Icon editions",
      "Trident 660",
      "Tiger 900",
      "Speed Twin"
    ],
    "Kawasaki": [
      "Ninja 300",
      "Ninja 500",
      "Ninja 650",
      "Ninja ZX-4R",
      "Ninja ZX-4RR",
      "Ninja ZX-6R",
      "Ninja ZX-10R",
      "Ninja H2 SX",
      "Ninja H2 SX SE",
      "Ninja 1100SX",
      "Z650RS",
      "Z900RS",
      "Z H2",
      "Z H2 SE",
      "Z900",
      "Eliminator",
      "Versys-X 300",
      "Versys 650",
      "Versys 1000",
      "Versys 1100",
      "W175 STREET",
      "W800",
      "KLX230",
      "KLX230R S",
      "KLX450R",
      "KX250",
      "KX450",
      "Vulcan S"
    ],
    "BMW Motorrad": [
      "G 310 R",
      "G 310 GS",
      "G 310 RR",
      "F 850 GS",
      "F 850 GS Adventure",
      "F 900 R",
      "F 900 XR",
      "S 1000 R",
      "S 1000 RR",
      "S 1000 XR",
      "M 1000 RR",
      "M 1000 R",
      "R 1250 GS",
      "R 1250 GS Adventure",
      "R 1250 RT",
      "R 1250 R",
      "R 1250 RS",
      "R 18",
      "R 18 Classic",
      "R 18 B",
      "R 18 Transcontinental",
      "R nineT",
      "R nineT Pure",
      "R nineT Scrambler",
      "R nineT Urban G/S",
      "K 1600 B",
      "K 1600 GTL",
      "C 400 GT",
      "CE 04",
      "CE 02"
    ],
    "Ola": [
      "Ola S1 Pro+ 5.3 kWh",
      "Ola S1 Pro+ 4 kWh",
      "Ola S1 Pro 4 kWh",
      "Ola S1 Pro 3 kWh",
      "Ola S1 X+ 4 kWh",
      "Ola S1 X 4 kWh",
      "Ola S1 X 3 kWh",
      "Ola S1 X 2 kWh",
      "Ola S1 Air",
      "Roadster X 2.5 kWh",
      "Roadster X 3.5 kWh",
      "Roadster X 4.5 kWh",
      "Roadster X+ 4.5 kWh",
      "Roadster X+ 9.1 kWh",
      "Roadster 3.5 kWh",
      "Roadster 4.5 kWh",
      "Roadster 6 kWh",
      "Roadster Pro 8 kWh",
      "Roadster Pro 16 kWh"
    ],
    "Ather": [
      "Ather Rizta",
      "Ather 450X",
      "Ather 450"
    ],
    "Ultraviolette": [
      "F77",
      "F77 Mach 2",
      "F77 Mach 2 Recon",
      "F77 SuperStreet"
    ],
    "Jawa": [
      "Jawa 42 Bobber",
      "Jawa 42",
      "Jawa 350",
      "Jawa 42 FJ",
      "Jawa Perak",
      "Classic",
      "Forty Two",
      "Perak"
    ],
    "Revolt Motors": ["RV400", "RV300"],
    "Emflux Motors": ["One"],
    "Srivaru Motors": ["Prana"],
    "FortyTwo Motors": ["42"],
    "Simple Energy": ["One"],
    "Ador Powertron": ["Scooty Zest"],
    "Log 9 Materials": ["InstaCharge"],
    "Matter": ["Aera"],
    "Tork Motors": ["Kratos R"],
    "Others": ["Other Models"]
  },


 "3-wheeler": {
  Bajaj: [
    "RE",
    "Maxima",
    "GoGo P5012",
    "GoGo P5009",
    "GoGo P7012",
    "Maxima XL Cargo E-TEC 12.0",
    "Maxima XL Cargo ETEC 9.0",
    "RE E-TEC 9.0",
    "Maxima Z",
    "Maxima X Wide",
    "Maxima C",
    "Qute"
  ],
  Piaggio: [
    "Ape",
    "Porter",
    "Apé Xtra HT 300cc Petrol",
    "Apé Xtra Classic Diesel",
    "Apé Xtra HD 599cc Diesel",
    "Apé Xtra LDX 230cc CNG",
    "Apé Xtra HT 300cc CNG",
    "Apé Auto Classic (Wide Body)",
    "Apé City+ 3-wheeler Auto",
    "Apé NXT+ (Small Body)",
    "Apé City Diesel 3-wheeler",
    "Apé Metro (Medium Body)",
    "Apé Auto+ (Extra Wide Body)",
    "Apé Auto Bada – CNG 300cc",
    "Ape Auto DXL (Extra Wide Body)",
    "Apé E-Xtra FX Max",
    "Apé Electric Cargo (Swappable Battery)",
    "Apé E-City FX Max (Swappable)",
    "Apé E-City FX Max (Fixed)"
  ],
  Mahindra: [
    "Alfa",
    "Treo Limited Edition",
    "e-Alfa Plus",
    "TREO",
    "Treo Yaari",
    "Alfa Dx Duo",
    "Alfa DX",
    "e-Alfa Cargo",
    "Treo Zor",
    "Zor Grand",
    "Alfa Plus Duo",
    "Alfa Plus"
  ],
  Atul: [
    "Shakti",
    "RIK",
    "RIK+",
    "GEM-PAXX DIESEL",
    "GEM-PAXX AQUA CNG",
    "GEM-CARGO DIESEL",
    "GEM-CARGO AQUA CNG",
    "ELITE PAXX",
    "ELITE CARGO",
    "Rik Twin",
    "ENERGIE²"
  ],
  TVS: [
    "King",
    "TVS King EV Max"
  ],
  "J S Auto": [
    "Victory Plus CNG",
    "Victory Plus Diesel",
    "NV CNG Passenger",
    "Victory CNG 3-Wheeler Passenger Carrier",
    "NV 3-Wheeler Passenger Auto Rickshaw",
    "E-Rickshaw King",
    "E-Rickshaw Ultra",
    "E-Rickshaw Star",
    "NV DIESEL LOADER BS-VI",
    "JSA NV CNG BS-VI",
    "Victory Plus Load Carrier",
    "Victory CNG Load Carrier",
    "JSA E-Cart"
  ],
  "Kerala Automobiles Ltd": [
    "Kerala Neem G",
    "Kerala Green Stream (E-Cart)",
    "KAL Mini E Cart",
    "KAL Ice Cream E Cart",
    "KAL Electric Buggy"
  ],
  "Euler Motors": [
    "HiLoad EV"
  ],
  Omega: [
    "Rage+ Qik",
    "Rage+",
    "Rage+ Frost",
    "Rage+ ATR",
    "Tipper",
    "Stream",
    "Stream City",
    "Stream City Qik",
    "Rage-NRG",
    "Stream-NRG",
    "Stream City NRG"
  ]
},

"cars": {
  "Maruti Suzuki": [
    "Swift",
    "Baleno",
    "Alto K10",
    "XL6",
    "Celerio",
    "Jimny",
    "Dzire",
    "Invicto",
    "Eeco",
    "Ignis",
    "Ertiga",
    "Grand Vitara",
    "S-Presso",
    "Fronx",
    "Ciaz",
    "WagonR",
    "Brezza"
  ],
  "Hyundai": [
    "Creta",
    "EXTER",
    "CRETA N LINE",
    "VENUE",
    "VENUE N LINE",
    "ALCAZAR",
    "TUCSON",
    "AURA",
    "VERNA",
    "GRAND I10 NIOS",
    "i20",
    "i20 N Line",
    "IONIQ 5",
    "CRETA ELECTRIC"
  ],
  "Tata": [
    "Nexon",
    "Curvv",
    "Altroz",
    "Tiago",
    "Tigor",
    "Punch",
    "Harrier",
    "Safari"
  ],
  "Mahindra": [
    "Thar",
    "THAR ROXX",
    "XUV 3XO",
    "SCORPIO-N",
    "XUV700",
    "SCORPIO CLASSIC",
    "BOLERO NEO",
    "BOLERO NEO PLUS",
    "BOLERO",
    "XUV400",
    "MARAZZO"
  ],
  "Honda": [
    "City",
    "All New Amaze",
    "Elevate",
    "City e:HEV",
    "Amaze - 2nd Gen"
  ],
  "Kia": [
    "Seltos",
    "Carens",
    "EV6",
    "Sonet",
    "Syros",
    "Carnival",
    "EV9",
    "Carens Clavis"
  ],
  "Toyota": [
    "Innova",
    "Glanza",
    "Urban Cruiser Taisor",
    "Rumion",
    "Urban Cruiser Hyryder",
    "Innova Crysta",
    "Innova Hycross",
    "Hilux",
    "Fortuner",
    "Legender",
    "Camry",
    "Vellfire",
    "Land Cruiser 3001"
  ],
  "Volkswagen": [
    "Golf GTI",
    "Tiguan R-Line",
    "Taigun",
    "Virtus"
  ],
  "Skoda": [
    "Kodiaq",
    "Kylaq",
    "Kushaq",
    "Slavia"
  ],
  "MG Motor": [
    "Hector",
    "Hector Plus 6 Seater",
    "Hector Plus 7 Seater",
    "Hector Blackstorm",
    "Hector Snowstorm",
    "Astor",
    "Gloster",
    "Gloster Blackstorm",
    "Gloster Storm Series",
    "ZS EV",
    "Comet EV",
    "Comet EV Blackstorm",
    "Windsor EV",
    "Windsor EV PRO"
  ],
  "Renault": [
    "KWID",
    "TRIBER",
    "KIGER"
  ],
  "Nissan": [
    "GT-R",
    "New Sunny",
    "Magnite",
    "Micra Active",
    "Micra",
    "Kicks",
    "Terrano",
    "New-Magnite",
    "Nissan X-Trail",
    "Nissan Magnite Geza"
  ],
  "Citroen": [
    "Basalt SUV Coupe Car",
    "Aircross",
    "C3",
    "New Ë-C3 All Electric",
    "C5 Aircross SUV"
  ],
  "BYD": [
    "SEALION 7",
    "eMAX 7",
    "ATTO 3",
    "SEAL"
  ],
  "Mercedes": [
    "A-Class Limousine",
    "C-Class",
    "E-Class",
    "S-Class",
    "Maybach S-Class",
    "AMG A 35 4MATIC",
    "AMG A 45 S 4MATIC+",
    "AMG E 53 4MATIC+",
    "E 63 S 4MATIC+",
    "AMG GT R",
    "AMG GT 63 S 4MATIC+ 4-Door Coupe",
    "EQA",
    "CLE Cabriolet",
    "AMG E 53 Cabriolet",
    "GLA",
    "GLC",
    "GLC Coupe",
    "GLE",
    "GLS",
    "Maybach GLS",
    "G-Class",
    "AMG GLA 35 4MATIC",
    "AMG GLC 43 4MATIC",
    "AMG GLE 53 4MATIC+ Coupe",
    "AMG G 63",
    "EQC",
    "EQS",
    "EQB",
    "AMG SL",
    "AMG GLC 43",
    "EQE SUV",
    "Maybach EQS SUV"
  ],
  "BMW": [
    "2 Series Gran Coupe",
    "3 Series Long Wheelbase",
    "5 Series Long Wheelbase",
    "7 Series Sedan",
    "Z4",
    "M2",
    "M340i",
    "M8 Competition Coupe",
    "M4 Competition Coupe with M xDrive",
    "M4 CS",
    "X1",
    "X3",
    "X5",
    "X7",
    "XM"
  ],
  "AUDI": [
    "A4",
    "A6",
    "A8 L",
    "Q3",
    "Q3 Sportback",
    "Q5",
    "Q7",
    "Q8",
    "RS Q8",
    "S5 Sportback",
    "e-tron",
    "e-tron GT",
    "RS e-tron GT",
    "Q8 e-tron",
    "Q8 Sportback e-tron"
  ],
  "Porsche": [
    "911",
    "718",
    "Taycan",
    "Panamera",
    "Macan",
    "Cayenne"
  ],
  "Lexus": [
    "NX",
    "RX",
    "LX",
    "ES",
    "LM"
  ],
  "JEEP": [
    "Compass",
    "Meridian",
    "Wrangler",
    "Grand Cherokee"
  ],
  "Land Rover": [
    "DEFENDER",
    "DISCOVERY",
    "RANGE ROVER",
    "RANGE ROVER SPORT",
    "RANGE ROVER VELAR",
    "RANGE ROVER EVOQUE",
    "DISCOVERY SPORT"
  ],
  "Volvo": [
    "EC40",
    "EX40",
    "XC90",
    "XC60",
    "S90"
  ],
  "Jaguar": [
    "F-PACE",
    "F-PACE SVR 575 EDITION",
    "F-PACE SVR EDITION 1988"
  ],
  "Lamborghini": [
    "Urus",
    "Revuelto",
    "Temerario",
    "Huracan EVO"
  ],
  "VinFast India": [
    "VF e34",
    "VF 3"
  ]
},

 "tractor": {
  "Mahindra": [
    "Arjun 555 DI",
    "Yuvo 575 DI",
    "Jivo 245 DI",
    "OJA",
    "YUVRAJ",
    "JIVO",
    "XP PLUS",
    "SP PLUS",
    "YUVO TECH +",
    "ARJUN",
    "NOVO",
    "265 DI SP Plus Tractor",
    "XP PLUS 265 Orchard Tractor",
    "305 Orchard Tractor",
    "NOVO 605 DI PP V1 Tractor",
    "ARJUN 605 DI i Tractor",
    "ARJUN 605 DI MS Tractor",
    "ARJUN 605 DI PP Tractor",
    "ARJUN 605 DI MS V1 Tractor",
    "OJA 3140 Tractor",
    "OJA 3136 Tractor",
    "OJA 3132 Tractor",
    "OJA 2130 Tractor",
    "OJA 2127 Tractor",
    "OJA 2124 Tractor",
    "OJA 2121 Tractor"
  ],
  "John Deere": [
    "5075E",
    "5065E",
    "5045D",
    "5310"
  ],
  "Sonalika": [
    "Tiger 50",
    "DI 745 III",
    "GT 20",
    "Sikander DI 35"
  ],
  "Escorts": [
    "Farmtrac 60",
    "Powertrac 439",
    "Steeltrac",
    "Farmtrac 45",
    "Josh 335",
    "MPT Jawan",
    "Farmtrac Atom series",
    "Farmtrac Champion Plus SuperMaxx",
    "Farmtrac Ultramaxx series",
    "Powertrac Euro series",
    "Powertrac ALT series",
    "Powertrac 434 series",
    "Powertrac 439 series",
    "Powertrac 445 series",
    "Powertrac 4455",
    "Digitrac"
  ],
  "Tafe": [
    "Massey Ferguson 241 DI",
    "Tafe 30 DI Orchard",
    "Massey Ferguson 7250",
    "Massey Ferguson Tractors",
    "Eicher Tractors",
    "TAFE Tractors",
    "IMT Tractors"
  ],
  "New Holland": [
    "3630 TX Plus",
    "3600-2 TX",
    "3037 TX",
    "5620 TX Plus"
  ],
  "Swaraj": [
    "744 FE",
    "Target 630 4WD",
    "Target 625 2WD",
    "Target 625 4WD",
    "717",
    "724 XM ORCHARD NT",
    "724 4WD",
    "724 XM ORCHARD",
    "724 XM",
    "825 XM",
    "733 FE",
    "834 XM",
    "735 FE",
    "735 XT",
    "843 XM",
    "742 XT",
    "744 FE 4WD",
    "744 XT",
    "855 FE",
    "855 FE 4WD",
    "963 FE",
    "969 FE"
  ],
  "Eicher": [
    "485 Super PLUS 4WD",
    "485 4WD",
    "251",
    "280 PLUS 4WD",
    "551 SUPER PLUS 2WD PRIMA G3",
    "551 4WD PRIMA G3",
    "551 HYDROMATIC 2WD PRIMA G3",
    "551 2WD PRIMA G3",
    "480 4WD PRIMA G3",
    "480 2WD PRIMA G3",
    "380 SUPER POWER 2WD PRIMA G3",
    "333 SUPER PLUS 2WD PRIMA G3",
    "557 4WD PRIMA G3",
    "557 2WD PRIMA G3",
    "380 4WD PRIMA G3",
    "380 2WD PRIMA G3",
    "5660",
    "557",
    "551 Super Plus",
    "551 Hydromatic",
    "548",
    "485 Super Plus",
    "485",
    "480",
    "380 Super Power",
    "380",
    "368",
    "333",
    "330",
    "242",
    "241",
    "188 4WD",
    "188",
    "733 FE",
    "312",
    "364",
    "371 Super Power",
    "5150",
    "650"
  ],
  "Force": [
    "Balwan 330",
    "Balwan 400",
    "Balwan 400 Super",
    "Balwan 450",
    "Balwan 500",
    "Balwan 550",
    "Sanman 5000",
    "Sanman 6000",
    "Sanman 6000 LT",
    "Orchard Mini",
    "Orchard Deluxe",
    "Orchard DLX LT",
    "Orchard 30",
    "Orchard 4x4",
    "Abhiman"
  ],
  "VST": [
    "MT 270 AGRIMASTER 2WD",
    "ZETOR 4211",
    "932 DI 4WD",
    "MT 225 - AJAI POWER PLUS",
    "MT 180 D",
    "929 DI EGT 4WD",
    "Zetor 5011",
    "932 DI",
    "918 4WD",
    "MT 224 - 1D 4WD",
    "Zetor 4511 2WD",
    "939 DI 4WD",
    "922 4WD",
    "MT 171 DI",
    "9054 DI Viraaj",
    "MT 171 DI - SAMRAAT",
    "MT180D / JAI-2W",
    "Viraaj XT 9045 DI",
    "VT 224 -1D",
    "927 4WD",
    "927",
    "932 IDI",
    "MT 270 High Torque",
    "Viraaj XP 9054 DI",
    "939",
    "5025 R Branson"
  ],
  "Captain": [
    "200 DI 4WD 20 HP Series",
    "200 DI 2WD 20 HP Series",
    "200 DI LS 20 HP Series",
    "223 4WD 22 HP Series",
    "250 DI 4WD 25 HP Series",
    "250 DI 2WD 25 HP Series",
    "280 DX 2WD 28 HP Series",
    "283 4WD 28 HP Series",
    "280 4WD 28 HP Series",
    "16.5 HP Series",
    "23 HP Series",
    "26 HP Series",
    "27 HP Series"
  ],
  "IndoFarm": [
    "1 Series",
    "2-Series",
    "3-Series",
    "4-Series"
  ],
  "Standard": [
    "DI 460",
    "DI 450",
    "DI 355",
    "DI 335",
    "DI 345",
    "DI 475",
    "DI 460 4WD",
    "DI 490"
  ],
  "ACE": [
    "AX-124 NS",
    "AX-124 4WD",
    "TC 5040-T",
    "AX-124",
    "14XW",
    "AB 163",
    "AX-130",
    "12XW",
    "5540",
    "3625",
    "DI 65 CHETAK",
    "DI-350 STAR",
    "DI-450 STAR",
    "DI 6565 AV TREM IV",
    "VEER 20",
    "VEER 3000 4WD",
    "NG Series Tractors",
    "Star Series Tractors",
    "DI 6500",
    "DI 7500",
    "DI 7575",
    "DI 9000",
    "DI 305 NG",
    "DI 550 NG",
    "DI 450 NG",
    "DI 6565 V2 4WD",
    "DI 6565 V2",
    "DI 6500 2WD",
    "DI 6565 4X4",
    "DI-550 STAR",
    "DI-350NG",
    "DI-854 NG",
    "Forma DI 450 Star",
    "DI-6500 NG V2 2WD"
  ],
  "Preet": [
    "6049",
    "4049",
    "4549",
    "2549",
    "6049 Super Yodha",
    "Super 4549",
    "A90 XT - AC Cabin",
    "10049 4WD",
    "955",
    "3549",
    "6049 4WD",
    "6549 4WD",
    "9049 AC - 4WD",
    "7549 - 4WD",
    "9049 - 4WD",
    "3049",
    "4549 CR 4WD",
    "4049 4WD",
    "7549",
    "2549 4WD",
    "3549 4WD",
    "6049 NT - 4WD",
    "8049",
    "8049 4WD",
    "4549 CR - 4WD",
    "955 4WD",
    "26 4WD (NSM)",
    "2025"
  ],
  "Cellestial": [
    "27 HP",
    "35 HP",
    "55 HP"
  ],
  "Volvo Trucks India": [
    "FM 420 4X2 Tractor",
    "FM 500 8X4 Electric Tractor",
    "FM 500 Puller 6X4",
    "FM 500 8X4 LNG Tractor",
    "FMX 500 8X4",
    "FM 500 8X4 Tractor",
    "FM 420 6X4 Tractor",
    "FM 500 6X2 Tractor",
    "FM 420 6X2 Tractor",
    "FM 500 6X4 Tractor",
    "FM 420 4X2 LNG Tractor"
  ]
},
  "truck": {
    "Tata Motors": [
      "Ultra",
      "Prima",
      "Signa",
      "Ace",
      "SIGNA 2821.T",
      "SIGNA 2823.T",
      "SIGNA 3125.T",
      "SIGNA 3525.T",
      "SIGNA 4225.T",
      "ULTRA T.6",
      "LPT 709G",
      "LPT 710",
      "LPT 712",
      "ULTRA T.7",
      "LPT 1916",
      "ULTRA T.19",
      "ULTRA K.14",
      "SIGNA 4830.TK.FBV",
      "PRIMA 2830.K HRT",
      "PRIMA 2830.K SRT",
      "PRIMA 3530.K HRT",
      "PRIMA 3530.K SRT",
      "LPK 1416",
      "LPK 2821.K FE+ RMC",
      "SIGNA 2830.K 8 Cum REPTO RMC",
      "PRIMA 2830.K REPTO",
      "SIGNA 4021.S",
      "SIGNA 4025.S",
      "PRIMA 5530.S",
      "SIGNA 5530.S",
      "710 LPT",
      "LPT GOLD 710",
      "SFC 712",
      "LPT 912",
      "ULTRA T.9",
      "LPT 1009G",
      "LPT 1012",
      "ULTRA T.11",
      "LPT 1109G",
      "LPT 1112",
      "LPT 1216",
      "LPT 1212",
      "LPT 1416",
      "LPT 1616",
      "LPT 1612G",
      "SIGNA 1923.K",
      "ULTRA T.18",
      "ULTRA T.16",
      "SIGNA 4623.S",
      "SIGNA 4830.T",
      "SIGNA 4930.T",
      "LPT 1816",
      "SFC 407 GOLD"
    ],
    "BharatBenz": [
      "2823C",
      "1617R",
      "4228R",
      "3123R",
      "MDT (10-19 tonnes)",
      "HDT R (28-48 tonnes)",
      "HDT RT (28-48 tonnes)",
      "HDT C (19-35 tonnes)",
      "HDT T (40-55 tonnes)"
    ],
    "Ashok Leyland": [
      "Boss 1115",
      "Ecomet 1015",
      "Bada Dost",
      "2820",
      "BOSS",
      "Partner Super",
      "ecomet Star",
      "ICV Tippers",
      "6X4 HB",
      "10X2 (GVW : 48T) HB",
      "8X2 (GVW : 35T) HB",
      "6X2 (GVW : 26T - 31T) HB",
      "4X2 (GVW : 19T) HB"
    ],
    "Eicher": [
      "Pro 3015",
      "Pro 2049",
      "Pro 6019",
      "Pro 8035XM",
      "Pro 6048",
      "Pro 2119 Truck",
      "Pro 2119 CNG",
      "Pro 3019",
      "Pro 3019 CNG",
      "Pro 6028",
      "Pro 6028 CNG",
      "Pro 6035",
      "Pro 6041",
      "Pro 6042",
      "Pro 6048XP",
      "Pro 2049 CNG",
      "Pro 2049 Plus",
      "Pro 2049XP",
      "Pro 2050",
      "Pro 2055",
      "Pro 2055K",
      "Pro 2059 Plus",
      "Pro 2059 CNG",
      "Pro 2059XP",
      "Pro 2059XP CNG",
      "Pro 2075",
      "Pro 2075 CNG",
      "Pro 2080XP",
      "Pro 2090",
      "Pro 2095",
      "Pro 2095XP Plus",
      "Pro 2109 Turbo+ CNG",
      "Pro 2110 6S",
      "Pro 2110 7S",
      "Pro 2110 CNG",
      "Pro 2110XP",
      "Pro 2110XP Plus",
      "Pro 2110XP Plus CNG",
      "Pro 2114XP",
      "Pro 2114XP CNG",
      "Pro 2118",
      "Pro 2118XP Plus",
      "Pro 3012",
      "Pro 3014",
      "Pro 3015 L32",
      "Pro 3015 L32 CNG",
      "Pro 3015XP",
      "Pro 3018",
      "Pro 3018 CNG",
      "Pro 3018 Plus",
      "Pro 3018XP Plus",
      "Pro X",
      "Pro 2049 EV",
      "Pro 2055 EV"
    ],
    "Volvo Trucks India": [
      "FMX 460",
      "FH 520",
      "FM 420",
      "FHL Electric",
      "FMX 460 8x4",
      "FMX 500 8x4",
      "FM 420 4x2",
      "FM 500 6x4 PULLER",
      "FM 420 LNG 4x2 Tractor"
    ],
    "Freightliner": [
      "Cascadia",
      "M2 106",
      "114SD",
      "122SD"
    ],
    "Peterbilt": [
      "579",
      "389",
      "567",
      "520"
    ],
    "Kenworth": [
      "T680",
      "T880",
      "W990",
      "T270"
    ],
    "Mack": [
      "Anthem",
      "Granite",
      "Pinnacle",
      "LR"
    ],
    "Mahindra": [
      "FURIO 10",
      "FURIO 11",
      "FURIO 12",
      "FURIO 14",
      "FURIO 14 HD",
      "FURIO 16",
      "FURIO 17",
      "Jayo",
      "Loadking Optimo",
      "FURIO 7"
    ],
    "SML Isuzu": [
      "Sartaj 5252 Diesel",
      "Sartaj GS 59 Diesel",
      "Sartaj HG 72 Diesel",
      "Samrat GS Diesel",
      "Samrat I2I2/I3I2 Diesel",
      "Samrat GS XT",
      "Supreme GS",
      "Prestige Diesel",
      "Sartaj 5252 CNG",
      "Samrat GS CNG",
      "Sartaj GS 59 CNG",
      "Sartaj HG 72 CNG",
      "Supreme Metro",
      "Prestige CNG"
    ],
    "Force Motors": [
      "Urbania",
      "Traveller Delivery Van",
      "Traveller Delivery Van Wider Body",
      "Trax Delivery Van"
    ],
    "Scania India": [
      "P410 8x4",
      "R500",
      "G410",
      "G 500 6x4",
      "G460",
      "R580 V8",
      "P360",
      "P 320 4x2",
      "P410 6x2",
      "G310 6x2",
      "R500 V8 Puller"
    ]},


"pickups": {
    "Ford": [
      "F-150",
      "F-250",
      "F-350",
      "F-150 Lightning",
      "Ranger",
      "Maverick"
    ],
    "Chevrolet": [
      "Silverado 1500",
      "Silverado 2500HD",
      "Colorado"
    ],
    "Ram": [
      "1500",
      "2500",
      "3500"
    ],
    "GMC": [
      "Sierra 1500",
      "Sierra 2500HD",
      "Canyon",
      "Hummer EV Pickup"
    ],
    "Toyota": [
      "Tundra",
      "Tacoma",
      "Hilux"
    ],
    "Nissan": [
      "Frontier",
      "Titan",
      "Titan XD"
    ],
    "Jeep": [
      "Gladiator"
    ],
    "Mahindra": [
      "Bolero Pik-Up",
      "Bolero Maxx Pik-Up",
      "Bolero MaXX Pik-Up City",
      "Bolero MaXX Pik-Up HD",
      "Bolero Pik-Up Extra Strong",
      "Bolero Pik-Up Extra Long",
      "Bolero Pik-Up 4x4",
      "Bolero Maxitruck Plus",
      "Bolero Maxitruck CNG",
      "Jeeto Mini Truck",
      "Supro Profit Truck Mini",
      "Supro Profit Truck Maxi"
    ],
    "Tata": [
      "Yodha",
      "Intra V30",
      "Yodha 2.0",
      "Yodha 1700",
      "Yodha Crew Cabin",
      "Yodha 4x4",
      "Yodha EX Crew Cabin",
      "Yodha EX Single Cab",
      "Yodha 2.0 CNG",
      "Intra V10",
      "Intra V20",
      "Intra V20 Gold",
      "Intra V50",
      "Intra V50 Gold",
      "Intra V70",
      "Intra EV Pickup Truck",
      "Ace",
      "Super Ace",
      "Ace Zip",
      "407 Pickup"
    ],
    "Ashok Leyland": [
      "Dost Strong",
      "Dost+",
      "Dost XL",
      "Dost CNG",
      "Bada Dost i2",
      "Bada Dost i3+",
      "Bada Dost i4",
      "Bada Dost i5",
      "Bada Dost CNG",
      "Saathi",
      "Partner 4 Tyre",
      "Partner 6 Tyre"
    ],
    "Force Motors": [
      "Trax Delivery Van",
      "Trax DCPU (Double Cabin Pickup)",
      "Kargo King",
      "Traveller Delivery Van",
      "Traveller Delivery Van Wider Body",
      "Urbania",
      "Trax Cruiser",
      "Trax Toofan",
      "Trax Ambulance",
      "Trax Crew Van",
      "Trax Cash Van",
      "Trax Police Van",
      "Traveller 3050WB",
      "Traveller 3350WB",
      "Traveller 3700WB",
      "Traveller 4020WB",
      "Traveller 4020WB Wider Body",
      "Citiline",
      "Gurkha"
    ],
    "Isuzu Motors India": [
      "D-Max",
      "V-Cross",
      "S-CAB Z",
      "MU-X",
      "Hi-Lander",
      "S-CAB"
    ],
    "Maruti Suzuki": [
      "Super Carry"
    ]
  },

  "trailer": {
    "Tata Motors": [
      "Signa 4021.S",
      "Signa 4023.S",
      "Signa 4025.S",
      "Signa 5530.S",
      "Signa 5532.S",
      "Signa 5530.S BSVI-4x2",
      "Signa 4623.S",
      "Signa 4830.T",
      "Signa 4930.T",
      "Prima 5530.S",
      "Prima 5530.S LX"
    ],
    "Ashok Leyland": [
      "6X4 with 3-axle Trailer",
      "4X2 with 2-axle Trailer",
      "4X2 with 3-axle Trailer"
    ],
    "Eicher Motors": [
      "Pro 6040",
      "Pro 6046",
      "Pro 6055XP",
      "Pro 6055XP 4x2",
      "Pro 8040XM",
      "Pro 8055",
      "Pro 8035XM"
    ],
    "BharatBenz": [
      "4023T",
      "4028T",
      "4032T",
      "4628T 4x2",
      "5032T",
      "5432T",
      "5528T 4x2",
      "5528T 6x4",
      "5532T 4x2",
      "5532T 6x4",
      "5532T HR"
    ],
    "AMW": [
      "3518 TR",
      "4923 TR",
      "4018 TR"
    ],
    "Scania India": [
      "R 500 6x2",
      "T 420 6x4",
      "R 500 6x4",
      "T 420 6x2",
      "G 410 6x2",
      "S 730 6x4",
      "G 410 6x4",
      "S 730 6x2",
      "P 320 6x2",
      "P 320 6x4"
    ],
    "Great Dane": [
      "Everest",
      "Champion",
      "Freedom"
    ],
    "Utility": [
      "3000R",
      "4000D-X",
      "VS2RA"
    ],
    "Wabash": [
      "DuraPlate",
      "ArcticLite",
      "Dry Van"
    ],
    "Hyundai Translead": [
      "HT Dry Van",
      "HT Reefer",
      "HT Flatbed"
    ],
    "Schmitz Cargobull": [
      "S.KO Cool",
      "S.CS Universal",
      "S.PR"
    ],
    "Krone": [
      "Box Liner",
      "Cool Liner",
      "Profi Liner"
    ]
},

 "earthmoving vehicle": {
    "Caterpillar": [
      "320 Excavator",
      "D6 Dozer",
      "950M Wheel Loader",
      "777G Off-Highway Truck",
      "320D3",
      "320D3 GC",
      "323D3",
      "313D2 L",
      "313",
      "315",
      "320",
      "330 UHD",
      "395",
      "424",
      "426",
      "120 Next Generation",
      "120MG",
      "D6R2",
      "D8R",
      "D8 (Tier 4/Stage V)",
      "D11T",
      "950GC",
      "980WL",
      "Hindustan 2021E",
      "216B3",
      "770G",
      "CS11 GC",
      "CS12 GC",
      "TH255C",
      "TH408D",
      "MH3032"
    ],
    "Komatsu": [
      "PC200-8 Excavator",
      "D65EX Dozer",
      "WA380 Wheel Loader",
      "HD785 Dump Truck"
    ],
    "JCB": [
      "3CX Backhoe Loader",
      "JS205 Excavator",
      "437 Wheel Loader",
      "220X Excavator",
      "NXT 205",
      "NXT 225",
      "345",
      "NXT 245 LR",
      "Tunnel Master",
      "19C-1E",
      "35Z HD",
      "37C HD",
      "Telehandlers",
      "Skid Steer Loaders",
      "Compactors",
      "Wheeled Loaders",
      "Hydrogen-Powered Backhoe Loader Prototype"
    ],
    "Hitachi": [
      "ZX200 Excavator",
      "ZX870 Excavator",
      "ZW220 Wheel Loader",
      "EH1100 Dump Truck"
    ],
    "Volvo": [
      "EC200D Excavator",
      "L120H Wheel Loader",
      "A40G Articulated Dump Truck",
      "EC950E",
      "EC750D",
      "EC550E",
      "EC480D",
      "EC380D",
      "EC350D",
      "EC300D",
      "EC250D",
      "EC210D",
      "EC210",
      "EC140D",
      "SD110",
      "DD90"
    ],
    "Mahindra": [
      "EarthMaster SX",
      "EarthMaster VX"
    ],
    "L&T Construction Equipment": [
      "9020 Wheel Loader",
      "9020 SX Wheel Loader",
      "WL9020 CEV Stage IV Wheel Loader",
      "491 Mini Tandem Compactor",
      "990HF Tandem Compactor",
      "1190D Soil Compactor",
      "2490HD Pneumatic Tyred Roller",
      "S315R Skid Steer Loader",
      "5590 Hydraulic Sensor Paver",
      "Motor Grader G90C"
    ],
    "Tata": [
      "EX 350LC Prime",
      "ZAXIS 370LCH",
      "ZAXIS 400MTH",
      "ZAXIS 490H Ultra",
      "ZAXIS 670H",
      "EX 1200V",
      "EX 1900-6",
      "EX 2600-7",
      "EX 2600-6",
      "EX 3600-7",
      "EX 5600-7",
      "EX 8000-7",
      "TL 304H",
      "TL 340H",
      "ZW 140",
      "ZW 225",
      "ZW 310-5A",
      "ZW 370-5A",
      "ZW 550"
    ]
  },
  
  "buses": {
    "Tata": [
      "Starbus",
      "Magna",
      "CityRide",
      "Marcopolo",
      "Cityride School",
      "Starbus School",
      "Starbus School AC",
      "Starbus School CNG",
      "Starbus School CNG AC",
      "Starbus Ultra School",
      "Starbus Ultra School AC",
      "Starbus Prime School",
      "Starbus 16 (Diesel)",
      "Starbus 24 (CNG)",
      "Starbus 36 CNG AC",
      "Starbus 24 EX, 32 EX, 36 EX (AC & Non-AC)",
      "Starbus Ultra 33, 36, 41, 51 (Diesel)",
      "Starbus Ultra 33 AC, 36 AC, 41 AC, 46 AC (Diesel)",
      "Cityride Ex 32, 36, 45 (Diesel)",
      "Ultra 9/7 EV",
      "Starbus 4/12 EV",
      "Ultra 9/9 EV"
    ],
    "Ashok Leyland": [
      "Viking",
      "Oyster",
      "Lynx",
      "Falcon",
      "3.5 M Intercity",
      "13.5 M Tourist",
      "12 M FE (Intercity, Staff, Diesel Tourist)",
      "Sunshine (School bus 32/39/49-seater)",
      "Cheetah (minibus)",
      "MiTR (School, Staff)",
      "12 M chassis (inter-state)",
      "Garud (15 m multi-axle chassis)"
    ],
    "Eicher": [
      "Skyline Pro",
      "Starline",
      "10.75H",
      "Sleeper 12.4 M",
      "Intercity 13.5 M AC Sleeper",
      "Coach 12.4 M",
      "Skyline 2075 H",
      "Skyline 2090 L",
      "Skyline 2112 M",
      "Starline 2050 C",
      "Starline 2050 D",
      "Starline 2070 E",
      "Starline 2075 H",
      "Starline 2090 L",
      "Skyline Pro 3009 H",
      "Skyline Pro 3010 L",
      "Skyline Pro 3011 L",
      "Skyline LIMO 18 Seater Push Back"
    ],
    "Volvo": [
      "B7R",
      "B8R",
      "9400",
      "B11R",
      "7900 Electric",
      "8900 Electric",
      "BZR Electric",
      "BZL Electric",
      "7900 Hybrid",
      "7900A (Articulated Hybrid)",
      "7900 (Diesel/CNG)",
      "8300",
      "8400",
      "8500 TX",
      "8500A",
      "8500LE",
      "8600",
      "8700 TX",
      "8700LE",
      "8700LEA",
      "9400LE",
      "9800",
      "5000",
      "7500",
      "7000",
      "7700",
      "7250",
      "7350",
      "7400",
      "7400XL",
      "7450",
      "7550",
      "7700A",
      "7800",
      "7900A",
      "8900",
      "9100",
      "9300",
      "9400XL",
      "9400PX",
      "9500",
      "9600",
      "9700",
      "9700 Double Decker",
      "9800 Double Decker",
      "9900",
      "B5L S-Charge",
      "B8L",
      "B8R Low Entry",
      "B13R"
    ],
    "BharatBenz": [
      "SHD 1623",
      "SHD 1017",
      "Tourino",
      "1017 School Bus",
      "1017 Staff Bus",
      "917 Chassis",
      "1017 Chassis",
      "1624 Chassis",
      "1824 Chassis"
    ],
    "Scania": [
      "Metrolink",
      "Citywide",
      "Touring",
      "Fencer",
      "Interlink",
      "OmniExpress",
      "OmniCity",
      "OmniLink",
      "OmniLine",
      "4-series",
      "K-series",
      "3-series",
      "N-series",
      "K-chassis HF Travel",
      "Fencer f1",
      "Fencer f6",
      "Fencer f18",
      "Citywide LF",
      "Citywide LE",
      "Citywide LEA"
    ],
    "Force Motors": [
      "Traveller 3050 WB",
      "Traveller 3350 WB",
      "Traveller 3700 WB",
      "Traveller 4020 WB",
      "Traveller Wider Body SWB",
      "Traveller Wider Body LWB",
      "Traveller Delivery Van 3050 WB",
      "Traveller Delivery Van 3350 WB",
      "Traveller Delivery Van 3700 WB",
      "Traveller Delivery Van 4020 WB",
      "Traveller Delivery Van 4020 WB Wider Body",
      "Traveller Ambulance 3350 WB",
      "Traveller School Bus 3050 WB",
      "Traveller School Bus 3350 WB",
      "Traveller School Bus 3700 WB",
      "Traveller School Bus 4020 WB",
      "Traveller Monobus Standard 4020 WB",
      "Traveller Monobus Standard 5200 WB",
      "Traveller Monobus School Bus 4020 WB",
      "Traveller Monobus School Bus 5200 WB"
    ],
    "Mahindra": [
      "Cruzio",
      "Cruzio Grande"
    ]
  }
};