
export const purchaseTypeOptions = [
  '1. Motorcycle/Scooter',
  '2. Cars/SUVs',
  '3. 3 Wheeler',
  '4. Pickups',
  '5. Truck',
  '6. Buses',
  '7. Tractor',
  '8. Trailer',
  '9. Earthmoving Vehicle',
  '10. None of the above',
];

export const positiveReasonOptions = [
  'Excellent mileage / fuel efficiency',
  'Affordable price / great value for money',
  'Strong brand reputation and high trust',
  'Highly recommended by friends, family, or mechanics',
  'Perfectly meets my purpose or usage needs',
  'Low maintenance and service cost',
  'Attractive design, look, and comfortable ride',
  'Easy financing and flexible EMI options',
  'Advanced safety features and modern technology',
  'Previous good experience with the brand / vehicle',
  'Other',
];

export const negativeReasonOptions = [
  'Poor mileage / fuel efficiency',
  'Expensive / not good value for money',
  'Weak brand reputation or lack of trust',
  'Not recommended by friends, family, or mechanics',
  'Does not meet my purpose or usage needs',
  'High maintenance and service cost',
  'Unappealing design, look, or uncomfortable ride',
  'Difficult financing or EMI options',
  'Lacks modern safety features or technology',
  'Previous bad experience with the brand / vehicle',
  'Other',
];

export const keyMap: Record<string, string> = {
  '1. Motorcycle/Scooter': '2-wheeler',
  '2. Cars/SUVs': 'cars',
  '3. 3 Wheeler': '3-wheeler',
  '4. Pickups': 'pickups',
  '5. Truck': 'truck',
  '6. Buses': 'buses',
  '7. Tractor': 'tractor',
  '8. Trailer': 'trailer',
  '9. Earthmoving Vehicle': 'earthmoving vehicle',
  '10. None of the above': '',
};

export const monthOptions = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
  "Don't remember",
];

export const vehicleConditionOptions = ['Brand New', 'Used'];

export const cityOptions = [
  'Ahmedabad',
  'Bangalore',
  'Chennai',
  'Delhi and NCR',
  'Hyderabad',
  'Kolkata',
  'Lucknow',
  'Mumbai',
  'Pune',
  'Other',
];

export const ageOptions = ['18-24', '25-34', '35-44', '45-54', '55 and Above'];

export const genderOptions = ['Male', 'Female'];





export const vehicleData: Record<string, Record<string, string[]>> = {
  "2-wheeler": {
    "Ador Powertron": ["Scooty Zest"],
    Ather: ["450", "450X", "Rizta"],
    Bajaj: [
      "Avenger 160 Street",
      "Avenger 220 Cruise",
      "Avenger 220 Street",
      "Bajaj Freedom 125 NG04",
      "Chetak",
      "CT 110X",
      "Dominar 250",
      "Dominar 400",
      "Platina 100",
      "Platina 110 Drum",
      "Pulsar 125",
      "Pulsar 150",
      "Pulsar 220F",
      "Pulsar N125",
      "Pulsar N150",
      "Pulsar N160",
      "Pulsar N250",
      "Pulsar NS125",
      "Pulsar NS160",
      "Pulsar NS200",
      "Pulsar NS400z",
      "Pulsar RS200",
    ],
    "BMW Motorrad": [
      "C 400 GT",
      "CE 02",
      "CE 04",
      "F 850 GS",
      "F 850 GS Adventure",
      "F 900 R",
      "F 900 XR",
      "G 310 GS",
      "G 310 R",
      "G 310 RR",
      "K 1600 B",
      "K 1600 GTL",
      "M 1000 R",
      "M 1000 RR",
      "R 1250 GS",
      "R 1250 GS Adventure",
      "R 1250 R",
      "R 1250 RS",
      "R 1250 RT",
      "R 18",
      "R 18 B",
      "R 18 Classic",
      "R 18 Transcontinental",
      "R nineT",
      "R nineT Pure",
      "R nineT Scrambler",
      "R nineT Urban G/S",
      "S 1000 R",
      "S 1000 RR",
      "S 1000 XR",
    ],
    "Emflux Motors": ["One"],
    "FortyTwo Motors": ["42"],
    "Harley Davidson": [
      "Breakout",
      "CVO Road Glide",
      "CVO Street Glide",
      "Fat Boy",
      "Forty-Eight",
      "Heritage Classic",
      "Iron 883",
      "Nightster",
      "Nightster Special",
      "Pan America 1250 Special",
      "Road Glide",
      "Sportster S",
      "Street 750",
      "Street Bob",
    ],
    Hero: [
      "Destini Prime",
      "Glamour",
      "Glamour XTEC",
      "HF 100",
      "HF Deluxe",
      "Karizma XMR",
      "Mavrick",
      "New Destini 125",
      "Pleasure+ XTEC",
      "Splendor+",
      "Splendor+ XTEC",
      "Splendor+ XTEC 2.0",
      "Super Splendor",
      "Super Splendor XTEC",
      "Xoom",
      "Xoom 125",
      "Xoom 160",
      "Xpulse 200 4V",
      "Xpulse 210",
      "Xtreme 125R",
      "Xtreme 160R",
      "Xtreme 160R 4V",
      "Xtreme 250R",
    ],
    Honda: [
      "Activa",
      "CB Shine",
      "CB300F",
      "CB300R",
      "CB350",
      "CB350 H'ness",
      "CB350RS",
      "Dio",
      "Goldwing Tour",
      "Hornet 2.0",
      "Livo",
      "NX200",
      "NX500",
      "Shine 100",
      "Shine 125",
      "SP 125",
      "SP 160",
      "Transalp",
      "Unicorn",
    ],
    Jawa: [
      "42",
      "Classic",
      "Forty Two",
      "Jawa 350",
      "Jawa 42 Bobber",
      "Jawa 42 FJ",
      "Perak",
    ],
    Kawasaki: [
      "Eliminator",
      "KLX230",
      "KLX230R S",
      "KLX450R",
      "KX250",
      "KX450",
      "Ninja 1100SX",
      "Ninja 300",
      "Ninja 500",
      "Ninja 650",
      "Ninja H2 SX",
      "Ninja H2 SX SE",
      "Ninja ZX-10R",
      "Ninja ZX-4R",
      "Ninja ZX-4RR",
      "Ninja ZX-6R",
      "Versys 1000",
      "Versys 1100",
      "Versys 650",
      "Versys-X 300",
      "Vulcan S",
      "W175 STREET",
      "W800",
      "Z H2",
      "Z H2 SE",
      "Z650RS",
      "Z900",
      "Z900RS",
    ],
    KTM: [
      "1290 Super Adventure S",
      "200 Duke",
      "250 Adventure",
      "250 Duke",
      "250 SX-F",
      "350 EXC-F Six Days",
      "390 Adventure",
      "390 Adventure X",
      "390 Duke",
      "390 Enduro R",
      "450 SX-F",
      "50 SX",
      "65 SX",
      "85 SX",
      "Duke 125",
      "RC 200",
      "RC 390",
      "RC GP",
    ],
    "Log 9 Materials": ["InstaCharge"],
    Mahindra: ["Mojo", "Mojo 300"],
    Matter: ["Aera"],
    Ola: [
      "Ola S1 Air",
      "Ola S1 Pro 3 kWh",
      "Ola S1 Pro 4 kWh",
      "Ola S1 Pro+ 4 kWh",
      "Ola S1 Pro+ 5.3 kWh",
      "Ola S1 X 2 kWh",
      "Ola S1 X 3 kWh",
      "Ola S1 X 4 kWh",
      "Ola S1 X+ 4 kWh",
      "Roadster 3.5 kWh",
      "Roadster 4.5 kWh",
      "Roadster 6 kWh",
      "Roadster Pro 16 kWh",
      "Roadster Pro 8 kWh",
      "Roadster X 2.5 kWh",
      "Roadster X 3.5 kWh",
      "Roadster X 4.5 kWh",
      "Roadster X+ 4.5 kWh",
      "Roadster X+ 9.1 kWh",
    ],
    "Revolt Motors": ["RV300", "RV400"],
    "Royal Enfield": [
      "Bear 650",
      "Bullet 350",
      "Classic 350",
      "Classic 650",
      "Continental GT 650",
      "Goan Classic 350",
      "Guerrilla 450",
      "Hunter 350",
      "Interceptor 650",
      "Meteor 350",
      "New Himalayan",
      "Scram 440",
      "Shotgun 650",
      "Super Meteor 650",
    ],
    "Simple Energy": ["One"],
    "Srivaru Motors": ["Prana"],
    Suzuki: [
      "Access",
      "Access 125",
      "Access 125 SE",
      "Avenis",
      "Burgman Street",
      "Burgman Street EX",
      "Gixxer 155",
      "Gixxer 250",
      "Gixxer SF 155",
      "Gixxer SF 250",
      "Hayabusa",
      "Intruder",
      "Katana",
      "V-Strom SX",
    ],
    "Tork Motors": ["Kratos R"],
    Triumph: [
      "Bonneville Bobber",
      "Bonneville SpeedMaster",
      "Bonneville T100",
      "Bonneville T120",
      "Daytona 660",
      "Icon editions",
      "New Speed T4",
      "New Speed Triple 1200 RS",
      "New Speed Twin 1200",
      "New Speed Twin 900",
      "Rocket 3 Storm",
      "Scrambler 1200",
      "Scrambler 400 X",
      "Scrambler 400 XC",
      "Scrambler 900",
      "Speed 400",
      "Speed Triple 1200 RS",
      "Speed Twin",
      "Street Triple 765",
      "Tiger 1200 Range",
      "Tiger 900",
      "Tiger 900 Range",
      "Tiger Sport 660",
      "Trident 660",
    ],
    TVS: [
      "Apache",
      "Apache RR 310",
      "Apache RTR 160",
      "Apache RTR 160 4V",
      "Apache RTR 200 4V",
      "Apache RTR 310",
      "iQube",
      "Jupiter",
      "Jupiter 125",
      "NTorq",
      "Radeon",
      "Raider",
      "Ronin",
      "Sport",
      "Star City Plus",
      "TVS X",
    ],
    Ultraviolette: [
      "F77",
      "F77 Mach 2",
      "F77 Mach 2 Recon",
      "F77 SuperStreet",
    ],
    Vespa: [
      "Vespa",
      "Vespa Dual",
      "Vespa Racing Sixties",
      "Vespa S",
      "Vespa S Tech",
      "Vespa SXL",
      "Vespa VXL",
      "Vespa ZX",
    ],
    Yamaha: [
      "Aerox 155",
      "Aerox 155 Version S",
      "Fascino",
      "Fascino 125 Fi",
      "FZ-Fi",
      "FZ-S Fi",
      "FZ-S Fi Hybrid",
      "FZ-S Fi Version 3.0",
      "FZ-S Fi Version 4.0",
      "FZ-S Fi Version 4.0 DLX",
      "FZ-X",
      "MT-03",
      "MT-15 Version 2.0",
      "MT-15 Version 2.0 MotoGP Edition",
      "R15 V4",
      "R15M",
      "R15M MotoGP Edition",
      "R15S",
      "RayZR 125 Fi",
      "RayZR 125 Fi Street Rally",
    ],
  },
  "3-wheeler": {
    Atul: [
      "ELITE CARGO",
      "ELITE PAXX",
      "ENERGIE²",
      "GEM-CARGO AQUA CNG",
      "GEM-CARGO DIESEL",
      "GEM-PAXX AQUA CNG",
      "GEM-PAXX DIESEL",
      "RIK",
      "RIK+",
      "Rik Twin",
      "Shakti",
    ],
    Bajaj: [
      "GoGo P5009",
      "GoGo P5012",
      "GoGo P7012",
      "Maxima",
      "Maxima C",
      "Maxima X Wide",
      "Maxima XL Cargo E-TEC 12.0",
      "Maxima XL Cargo ETEC 9.0",
      "Maxima Z",
      "Qute",
      "RE",
      "RE E-TEC 9.0",
    ],
    "Euler Motors": ["HiLoad EV"],
    "J S Auto": [
      "E-Rickshaw King",
      "E-Rickshaw Star",
      "E-Rickshaw Ultra",
      "JSA E-Cart",
      "JSA NV CNG BS-VI",
      "NV 3-Wheeler Passenger Auto Rickshaw",
      "NV CNG Passenger",
      "NV DIESEL LOADER BS-VI",
      "Victory CNG 3-Wheeler Passenger Carrier",
      "Victory CNG Load Carrier",
      "Victory Plus CNG",
      "Victory Plus Diesel",
      "Victory Plus Load Carrier",
    ],
    "Kerala Automobiles Ltd": [
      "KAL Electric Buggy",
      "KAL Ice Cream E Cart",
      "KAL Mini E Cart",
      "Kerala Green Stream (E-Cart)",
      "Kerala Neem G",
    ],
    Mahindra: [
      " Alfa",
      "Alfa DX",
      "Alfa Dx Duo",
      "Alfa Plus",
      "Alfa Plus Duo",
      "e-Alfa Cargo",
      "e-Alfa Plus",
      "Treo",
      "Treo Limited Edition",
      "Treo Yaari",
      "Treo Zor",
      "Zor Grand",
    ],
    Omega: [
      "Rage+",
      "Rage+ ATR",
      "Rage+ Frost",
      "Rage+ Qik",
      "Rage-NRG",
      "Stream",
      "Stream City",
      "Stream City NRG",
      "Stream-NRG",
      "Tipper",
    ],
    Piaggio: [
      "Apé Auto Bada – CNG 300cc",
      "Apé Auto Classic (Wide Body)",
      "Apé Auto+ (Extra Wide Body)",
      "Apé City Diesel 3-wheeler",
      "Apé City+ 3-wheeler Auto",
      "Apé E-City FX Max (Fixed)",
      "Apé E-City FX Max (Swappable)",
      "Apé Electric Cargo (Swappable Battery)",
      "Apé E-Xtra FX Max",
      "Apé Metro (Medium Body)",
      "Apé NXT+ (Small Body)",
      "Ape",
      "Ape Auto DXL (Extra Wide Body)",
      "Apé Xtra Classic Diesel",
      "Apé Xtra HD 599cc Diesel",
      "Apé Xtra HT 300cc CNG",
      "Apé Xtra HT 300cc Petrol",
      "Apé Xtra LDX 230cc CNG",
      "Porter",
    ],
    TVS: ["King", "TVS King EV Max"],
  },
  buses: {
    "Ashok Leyland": [
      "12 M chassis (inter-state)",
      "12 M FE (Intercity, Staff, Diesel Tourist)",
      "13.5 M Tourist",
      "3.5 M Intercity",
      "Cheetah (minibus)",
      "Falcon",
      "Garud (15 m multi-axle chassis)",
      "Lynx",
      "MiTR (School, Staff)",
      "Oyster",
      "Sunshine (School bus 32/39/49-seater)",
      "Viking",
    ],
    BharatBenz: [
      "1017 Chassis",
      "1017 School Bus",
      "1017 Staff Bus",
      "1624 Chassis",
      "1824 Chassis",
      "917 Chassis",
      "SHH 1017",
      "SHH 1623",
      "Tourino",
    ],
    Eicher: [
      "10.75H",
      "Coach 12.4 M",
      "Intercity 13.5 M AC Sleeper",
      "Skyline 2075 H",
      "Skyline 2090 L",
      "Skyline 2112 M",
      "Skyline LIMO 18 Seater Push Back",
      "Skyline Pro",
      "Skyline Pro 3009 H",
      "Skyline Pro 3010 L",
      "Skyline Pro 3011 L",
      "Sleeper 12.4 M",
      "Starline",
      "Starline 2050 C",
      "Starline 2050 D",
      "Starline 2070 E",
      "Starline 2075 H",
      "Starline 2090 L",
    ],
    "Force Motors": [
      "Traveller 3050 WB",
      "Traveller 3350 WB",
      "Traveller 3700 WB",
      "Traveller 4020 WB",
      "Traveller Ambulance 3350 WB",
      "Traveller Delivery Van 3050 WB",
      "Traveller Delivery Van 3350 WB",
      "Traveller Delivery Van 3700 WB",
      "Traveller Delivery Van 4020 WB",
      "Traveller Delivery Van 4020 WB Wider Body",
      "Traveller Monobus School Bus 4020 WB",
      "Traveller Monobus School Bus 5200 WB",
      "Traveller Monobus Standard 4020 WB",
      "Traveller Monobus Standard 5200 WB",
      "Traveller School Bus 3050 WB",
      "Traveller School Bus 3350 WB",
      "Traveller School Bus 3700 WB",
      "Traveller School Bus 4020 WB",
      "Traveller Wider Body LWB",
      "Traveller Wider Body SWB",
    ],
    Mahindra: ["Cruzio", "Cruzio Grande"],
    Scania: [
      "3-series",
      "4-series",
      "Citywide",
      "Citywide LE",
      "Citywide LF",
      "Citywide LEA",
      "Fencer",
      "Fencer f1",
      "Fencer f18",
      "Fencer f6",
      "Interlink",
      "K-chassis HF Travel",
      "K-series",
      "Metrolink",
      "N-series",
      "OmniCity",
      "OmniExpress",
      "OmniLine",
      "Touring",
    ],
    Tata: [
      "CityRide",
      "Cityride Ex 32, 36, 45 (Diesel)",
      "Cityride School",
      "Magna",
      "Marcopolo",
      "Starbus",
      "Starbus 16 (Diesel)",
      "Starbus 24 (CNG)",
      "Starbus 24 EX, 32 EX, 36 EX (AC & Non-AC)",
      "Starbus 36 CNG AC",
      "Starbus Prime School",
      "Starbus School",
      "Starbus School AC",
      "Starbus School CNG",
      "Starbus School CNG AC",
      "Starbus Ultra 33, 36, 41, 51 (Diesel)",
      "Starbus Ultra 33 AC, 36 AC, 41 AC, 46 AC (Diesel)",
      "Starbus Ultra School",
      "Starbus Ultra School AC",
      "Ultra 9/7 EV",
      "Ultra 9/9 EV",
    ],
    Volvo: [
      "5000",
      "7000",
      "7250",
      "7350",
      "7400",
      "7400XL",
      "7450",
      "7500",
      "7550",
      "7700",
      "7700A",
      "7800",
      "7900 (Diesel/CNG)",
      "7900 Electric",
      "7900 Hybrid",
      "7900A",
      "7900A (Articulated Hybrid)",
      "8300",
      "8400",
      "8500 TX",
      "8500A",
      "8500LE",
      "8600",
      "8700 TX",
      "8700LE",
      "8700LEA",
      "8900",
      "8900 Electric",
      "9100",
      "9300",
      "9400",
      "9400LE",
      "9400PX",
      "9400XL",
      "9500",
      "9600",
      "9700",
      "9700 Double Decker",
      "9800",
      "9800 Double Decker",
      "9900",
      "B11R",
      "B13R",
      "B5L S-Charge",
      "B7R",
      "B8L",
      "B8R",
      "B8R Low Entry",
      "BZL Electric",
      "BZR Electric",
    ],
  },
  cars: {
    AUDI: [
      "A4",
      "A6",
      "A8 L",
      "e-tron",
      "e-tron GT",
      "Q3",
      "Q3 Sportback",
      "Q5",
      "Q7",
      "Q8",
      "Q8 e-tron",
      "Q8 Sportback e-tron",
      "RS e-tron GT",
      "RS Q8",
      "S5 Sportback",
    ],
    BMW: [
      "2 Series Gran Coupe",
      "3 Series Long Wheelbase",
      "5 Series Long Wheelbase",
      "7 Series Sedan",
      "M2",
      "M340i",
      "M4 Competition Coupe with M xDrive",
      "M4 CS",
      "M8 Competition Coupe",
      "X1",
      "X3",
      "X5",
      "X7",
      "XM",
      "Z4",
    ],
    BYD: ["ATTO 3", "eMAX 7", "SEAL", "SEALION 7"],
    Citroen: [
      "Aircross",
      "Basalt SUV Coupe Car",
      "C3",
      "C5 Aircross SUV",
      "New Ë-C3 All Electric",
    ],
    Honda: [
      "All New Amaze",
      "Amaze - 2nd Gen",
      "City",
      "City e:HEV",
      "Elevate",
    ],
    Hyundai: [
      "ALCAZAR",
      "AURA",
      "CRETA ELECTRIC",
      "CRETA N LINE",
      "Creta",
      "EXTER",
      "GRAND I10 NIOS",
      "i20",
      "i20 N Line",
      "IONIQ 5",
      "TUCSON",
      "VENUE",
      "VENUE N LINE",
      "VERNA",
    ],
    Jaguar: [
      "F-PACE",
      "F-PACE SVR 575 EDITION",
      "F-PACE SVR EDITION 1988",
    ],
    JEEP: ["Compass", "Grand Cherokee", "Meridian", "Wrangler"],
    Kia: [
      "Carens",
      "Carens Clavis",
      "Carnival",
      "EV6",
      "EV9",
      "Seltos",
      "Sonet",
      "Syros",
    ],
    Lamborghini: ["Huracan EVO", "Revuelto", "Temerario", "Urus"],
    "Land Rover": [
      "DEFENDER",
      "DISCOVERY",
      "DISCOVERY SPORT",
      "RANGE ROVER",
      "RANGE ROVER EVOQUE",
      "RANGE ROVER SPORT",
      "RANGE ROVER VELAR",
    ],
    Lexus: ["ES", "LM", "LX", "NX", "RX"],
    Mahindra: [
      "BOLERO",
      "BOLERO NEO",
      "BOLERO NEO PLUS",
      "MARAZZO",
      "SCORPIO CLASSIC",
      "SCORPIO-N",
      "Thar",
      "THAR ROXX",
      "XUV 3XO",
      "XUV400",
      "XUV700",
    ],
    "Maruti Suzuki": [
      "Alto K10",
      "Baleno",
      "Brezza",
      "Celerio",
      "Ciaz",
      "Dzire",
      "Eeco",
      "Ertiga",
      "Fronx",
      "Grand Vitara",
      "Ignis",
      "Invicto",
      "Jimny",
      "S-Presso",
      "Swift",
      "WagonR",
      "XL6",
    ],
    "MG Motor": [
      "Astor",
      "Comet EV",
      "Comet EV Blackstorm",
      "Gloster",
      "Gloster Blackstorm",
      "Gloster Storm Series",
      "Hector",
      "Hector Blackstorm",
      "Hector Plus 6 Seater",
      "Hector Plus 7 Seater",
      "Hector Snowstorm",
      "Windsor EV",
      "Windsor EV PRO",
      "ZS EV",
    ],
    Mercedes: [
      "A-Class Limousine",
      "AMG A 35 4MATIC",
      "AMG A 45 S 4MATIC+",
      "AMG E 53 4MATIC+",
      "AMG E 53 Cabriolet",
      "AMG G 63",
      "AMG GLA 35 4MATIC",
      "AMG GLC 43",
      "AMG GLC 43 4MATIC",
      "AMG GLE 53 4MATIC+ Coupe",
      "AMG GT 63 S 4MATIC+ 4-Door Coupe",
      "AMG GT R",
      "AMG SL",
      "C-Class",
      "CLE Cabriolet",
      "E 63 S 4MATIC+",
      "E-Class",
      "EQA",
      "EQB",
      "EQC",
      "EQE SUV",
      "EQS",
      "G-Class",
      "GLA",
      "GLC",
      "GLC Coupe",
      "GLE",
      "GLS",
      "Maybach EQS SUV",
      "Maybach GLS",
      "Maybach S-Class",
      "S-Class",
    ],
    Nissan: [
      "GT-R",
      "Kicks",
      "Magnite",
      "Micra",
      "Micra Active",
      "New Sunny",
      "New-Magnite",
      "Nissan Magnite Geza",
      "Nissan X-Trail",
      "Terrano",
    ],
    Porsche: ["718", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
    Renault: ["KIGER", "KWID", "TRIBER"],
    Skoda: ["Kodiaq", "Kushaq", "Kylaq", "Slavia"],
    Tata: [
      "Altroz",
      "Curvv",
      "Harrier",
      "Nexon",
      "Punch",
      "Safari",
      "Tiago",
      "Tigor",
    ],
    Toyota: [
      "Camry",
      "Fortuner",
      "Glanza",
      "Hilux",
      "Innova",
      "Innova Crysta",
      "Innova Hycross",
      "Land Cruiser 3001",
      "Legender",
      "Rumion",
      "Urban Cruiser Hyryder",
      "Urban Cruiser Taisor",
      "Vellfire",
    ],
    "VinFast India": ["VF 3", "VF e34"],
    Volkswagen: ["Golf GTI", "Taigun", "Tiguan R-Line", "Virtus"],
    Volvo: ["EC40", "EX40", "S90", "XC60", "XC90"],
  },
  "earthmoving vehicle": {
    Caterpillar: [
      "120 Next Generation",
      "120MG",
      "216B3",
      "313",
      "313D2 L",
      "315",
      "320",
      "320 Excavator",
      "320D3",
      "320D3 GC",
      "323D3",
      "330 UHD",
      "395",
      "424",
      "426",
      "770G",
      "777G Off-Highway Truck",
      "950GC",
      "950M Wheel Loader",
      "980WL",
      "CS11 GC",
      "CS12 GC",
      "D11T",
      "D6 Dozer",
      "D6R2",
      "D8 (Tier 4/Stage V)",
      "D8R",
      "Hindustan 2021E",
      "MH3032",
      "TH255C",
      "TH408D",
    ],
    Hitachi: [
      "EH1100 Dump Truck",
      "ZH200 Excavator",
      "ZW220 Wheel Loader",
      "ZX870 Excavator",
    ],
    JCB: [
      "19C-1E",
      "220X Excavator",
      "3CX Backhoe Loader",
      "345",
      "35Z HD",
      "37C HD",
      "437 Wheel Loader",
      "Compactors",
      "Hydrogen-Powered Backhoe Loader Prototype",
      "JS205 Excavator",
      "NXT 205",
      "NXT 225",
      "NXT 245 LR",
      "Skid Steer Loaders",
      "Telehandlers",
      "Tunnel Master",
      "Wheeled Loaders",
    ],
    Komatsu: [
      "D65EX Dozer",
      "HD785 Dump Truck",
      "PC200-8 Excavator",
      "WA380 Wheel Loader",
    ],
    "L&T Construction Equipment": [
      "1190D Soil Compactor",
      "2490HD Pneumatic Tyred Roller",
      "491 Mini Tandem Compactor",
      "5590 Hydraulic Sensor Paver",
      "9020 SX Wheel Loader",
      "9020 Wheel Loader",
      "990HF Tandem Compactor",
      "Motor Grader G90C",
      "S315R Skid Steer Loader",
      "WL9020 CEV Stage IV Wheel Loader",
    ],
    Mahindra: ["EarthMaster SX", "EarthMaster VX"],
    Tata: [
      "EX 1200V",
      "EX 1900-6",
      "EX 2600-6",
      "EX 2600-7",
      "EX 350LC Prime",
      "EX 3600-7",
      "EX 5600-7",
      "EX 8000-7",
      "TL 304H",
      "TL 340H",
      "ZAXIS 370LCH",
      "ZAXIS 400MTH",
      "ZAXIS 490H Ultra",
      "ZAXIS 670H",
      "ZW 140",
      "ZW 225",
      "ZW 310-5A",
      "ZW 370-5A",
      "ZW 550",
    ],
    Volvo: [
      "A40G Articulated Dump Truck",
      "DD90",
      "EC140D",
      "EC200D Excavator",
      "EC210",
      "EC210D",
      "EC250D",
      "EC300D",
      "EC350D",
      "EC380D",
      "EC480D",
      "EC550E",
      "EC750D",
      "EC950E",
      "L120H Wheel Loader",
      "SD110",
    ],
  },
  pickups: {
    "Ashok Leyland": [
      "Bada Dost CNG",
      "Bada Dost i2",
      "Bada Dost i3+",
      "Bada Dost i4",
      "Bada Dost i5",
      "Dost CNG",
      "Dost Strong",
      "Dost XL",
      "Dost+",
      "Partner 4 Tyre",
      "Partner 6 Tyre",
      "Saathi",
    ],
    Chevrolet: ["Colorado", "Silverado 1500", "Silverado 2500HD"],
    Ford: ["F-150", "F-150 Lightning", "F-250", "F-350", "Maverick", "Ranger"],
    "Force Motors": [
      "Citiline",
      "Gurkha",
      "Trax Ambulance",
      "Trax Cash Van",
      "Trax Crew Van",
      "Trax Cruiser",
      "Trax DCPU (Double Cabin Pickup)",
      "Trax Delivery Van",
      "Trax Police Van",
      "Trax Toofan",
      "Traveller 3050WB",
      "Traveller 3350WB",
      "Traveller 3700WB",
      "Traveller 4020WB",
      "Traveller 4020WB Wider Body",
      "Traveller Delivery Van",
      "Traveller Delivery Van Wider Body",
      "Urbania",
    ],
    GMC: ["Canyon", "Hummer EV Pickup", "Sierra 1500", "Sierra 2500HD"],
    "Isuzu Motors India": [
      "D-Max",
      "Hi-Lander",
      "MU-X",
      "S-CAB",
      "S-CAB Z",
      "V-Cross",
    ],
    Jeep: ["Gladiator"],
    Mahindra: [
      "Bolero MaXX Pik-Up City",
      "Bolero MaXX Pik-Up HD",
      "Bolero Maxitruck CNG",
      "Bolero Maxitruck Plus",
      "Bolero Pik-Up 4x4",
      "Bolero Pik-Up Extra Long",
      "Bolero Pik-Up Extra Strong",
      "Bolero Pik-Up",
      "Jeeto Mini Truck",
      "Supro Profit Truck Maxi",
      "Supro Profit Truck Mini",
    ],
    "Maruti Suzuki": ["Super Carry"],
    Nissan: ["Frontier", "Titan", "Titan XD"],
    Ram: ["1500", "2500", "3500"],
    Tata: [
      "407 Pickup",
      "Ace",
      "Ace Zip",
      "Intra EV Pickup Truck",
      "Intra V10",
      "Intra V20",
      "Intra V20 Gold",
      "Intra V30",
      "Intra V50",
      "Intra V50 Gold",
      "Intra V70",
      "Super Ace",
      "Yodha",
      "Yodha 1700",
      "Yodha 2.0",
      "Yodha 2.0 CNG",
      "Yodha 4x4",
      "Yodha Crew Cabin",
      "Yodha EX Crew Cabin",
      "Yodha EX Single Cab",
    ],
    Toyota: ["Hilux", "Tacoma", "Tundra"],
  },
  tractor: {
    ACE: [
      "12XW",
      "14XW",
      "5540",
      "3625",
      "AB 163",
      "AX-124",
      "AX-124 4WD",
      "AX-124 NS",
      "DI 305 NG",
      "DI 350 STAR",
      "DI-350NG",
      "DI 450 NG",
      "DI 450 STAR",
      "DI 65 CHETAK",
      "DI 6500",
      "DI 6500 NG V2 2WD",
      "DI 6565 4X4",
      "DI 6565 V2",
      "DI 6565 V2 4WD",
      "DI 7500",
      "DI 7575",
      "DI 9000",
      "DI-550 STAR",
      "DI-854 NG",
      "Forma DI 450 Star",
      "NG Series Tractors",
      "Star Series Tractors",
      "TC 5040-T",
      "VEER 20",
      "VEER 3000 4WD",
    ],
    Captain: [
      "16.5 HP Series",
      "200 DI 2WD 20 HP Series",
      "200 DI 4WD 20 HP Series",
      "200 DI LS 20 HP Series",
      "223 4WD 22 HP Series",
      "23 HP Series",
      "250 DI 2WD 25 HP Series",
      "250 DI 4WD 25 HP Series",
      "26 HP Series",
      "27 HP Series",
      "280 4WD 28 HP Series",
      "280 DX 2WD 28 HP Series",
      "283 4WD 28 HP Series",
    ],
    Cellestial: ["27 HP", "35 HP", "55 HP"],
    Eicher: [
      "188",
      "188 4WD",
      "241",
      "242",
      "251",
      "280 PLUS 4WD",
      "312",
      "330",
      "333",
      "333 SUPER PLUS 2WD PRIMA G3",
      "364",
      "368",
      "371 Super Power",
      "380",
      "380 2WD PRIMA G3",
      "380 4WD PRIMA G3",
      "380 SUPER POWER 2WD PRIMA G3",
      "480",
      "480 2WD PRIMA G3",
      "480 4WD PRIMA G3",
      "485",
      "485 4WD",
      "485 Super Plus",
      "485 SUPER PLUS 4WD",
      "5150",
      "548",
      "551 2WD PRIMA G3",
      "551 4WD PRIMA G3",
      "551 HYDROMATIC 2WD PRIMA G3",
      "551 Super Plus",
      "551 SUPER PLUS 2WD PRIMA G3",
      "557",
      "557 2WD PRIMA G3",
      "557 4WD PRIMA G3",
      "5660",
      "650",
      "733 FE",
    ],
    Escorts: [
      "Digitrac",
      "Farmtrac 45",
      "Farmtrac 60",
      "Farmtrac Atom series",
      "Farmtrac Champion Plus SuperMaxx",
      "Farmtrac Ultramaxx series",
      "Josh 335",
      "MPT Jawan",
      "Powertrac 434 series",
      "Powertrac 439",
      "Powertrac 439 series",
      "Powertrac 445",
      "Powertrac 4455",
      "Powertrac ALT series",
      "Powertrac Euro series",
      "Steeltrac",
    ],
    Force: [
      "Abhiman",
      "Balwan 330",
      "Balwan 400",
      "Balwan 400 Super",
      "Balwan 450",
      "Balwan 500",
      "Balwan 550",
      "Orchard 30",
      "Orchard 4x4",
      "Orchard Deluxe",
      "Orchard DLX LT",
      "Sanman 5000",
      "Sanman 5000 LT",
      "Sanman 6000",
      "Sanman 6000 LT",
    ],
    IndoFarm: ["1 Series", "2-Series", "3-Series", "4-Series"],
    "John Deere": ["5045D", "5065E", "5075E", "5310"],
    Mahindra: [
      "265 DI SP Plus Tractor",
      "305 Orchard Tractor",
      "ARJUN",
      "Arjun 555 DI",
      "ARJUN 605 DI i Tractor",
      "ARJUN 605 DI MS Tractor",
      "ARJUN 605 DI MS V1 Tractor",
      "ARJUN 605 DI PP Tractor",
      "JIVO",
      "Jivo 245 DI",
      "NOVO",
      "NOVO 605 DI PP V1 Tractor",
      "OJA",
      "OJA 2121 Tractor",
      "OJA 2124 Tractor",
      "OJA 2127 Tractor",
      "OJA 2130 Tractor",
      "OJA 3132 Tractor",
      "OJA 3136 Tractor",
      "OJA 3140 Tractor",
      "SP PLUS",
      "XP PLUS",
      "XP PLUS 265 Orchard Tractor",
      "Yuvo 575 DI",
      "YUVRAJ",
      "YUVO TECH +",
    ],
    "New Holland": [
      "3037 TX",
      "3600-2 TX",
      "3630 TX Plus",
      "5620 TX Plus",
    ],
    Preet: [
      "10049 4WD",
      "2025",
      "2549",
      "2549 4WD",
      "26 4WD (NSM)",
      "3049",
      "3549",
      "3549 4WD",
      "4049",
      "4049 4WD",
      "4549",
      "4549 CR - 4WD",
      "4549 CR 4WD",
      "6049",
      "6049 4WD",
      "6049 NT - 4WD",
      "6049 Super Yodha",
      "6549 4WD",
      "7549",
      "7549 - 4WD",
      "8049",
      "8049 4WD",
      "9049 - 4WD",
      "9049 AC - 4WD",
      "955",
      "955 4WD",
      "A90 XT - AC Cabin",
      "Super 4549",
    ],
    Sonalika: ["DI 745 III", "GT 20", "Sikander DI 35", "Tiger 50"],
    Standard: [
      "DI 335",
      "DI 345",
      "DI 355",
      "DI 450",
      "DI 460",
      "DI 460 4WD",
      "DI 475",
      "DI 490",
    ],
    Swaraj: [
      "717",
      "724 4WD",
      "724 XM",
      "724 XM ORCHARD",
      "724 XM ORCHARD NT",
      "733 FE",
      "735 FE",
      "735 XT",
      "744 FE",
      "744 FE 4WD",
      "744 XT",
      "825 XM",
      "834 XM",
      "843 XM",
      "855 FE",
      "855 FE 4WD",
      "963 FE",
      "969 FE",
      "Target 625 2WD",
      "Target 625 4WD",
      "Target 630 4WD",
    ],
    Tafe: [
      "Eicher Tractors",
      "IMT Tractors",
      "Massey Ferguson 241 DI",
      "Massey Ferguson 7250",
      "Massey Ferguson Tractors",
      "Tafe 30 DI Orchard",
      "TAFE Tractors",
    ],
    VST: [
      "5025 R Branson",
      "9054 DI Viraaj",
      "918 4WD",
      "922 4WD",
      "927",
      "927 4WD",
      "932 DI",
      "932 DI 4WD",
      "932 IDI",
      "939",
      "939 DI 4WD",
      "MT 171 DI",
      "MT 171 DI - SAMRAAT",
      "MT 180 D",
      "MT 224 - 1D 4WD",
      "MT 225 - AJAI POWER PLUS",
      "MT 270 AGRIMASTER 2WD",
      "MT 270 High Torque",
      "MT180D / JAI-2W",
      "Viraaj XP 9054 DI",
      "Viraaj XT 9045 DI",
      "VT 224 -1D",
      "Zetor 4211",
      "Zetor 4511",
      "ZETOR 5011",
    ],
    "Volvo Trucks India": [
      "FM 420 4X2 LNG Tractor",
      "FM 420 4X2 Tractor",
      "FM 420 6X2 Tractor",
      "FM 420 6X4 Tractor",
      "FM 500 6X2 Tractor",
      "FM 500 6X4 Tractor",
      "FM 500 8X4 Electric Tractor",
      "FM 500 8X4 LNG Tractor",
      "FM 500 Puller 6X4",
      "FMX 500 8X4",
    ],
  },
  trailer: {
    AMW: ["3518 TR", "4018 TR", "4923 TR"],
    "Ashok Leyland": [
      "4X2 with 2-axle Trailer",
      "4X2 with 3-axle Trailer",
      "6X4 with 3-axle Trailer",
    ],
    BharatBenz: [
      "4023T",
      "4028T",
      "4032T",
      "4628T 4x2",
      "5032T",
      "5432T",
      "5528T 4x2",
      "5528T 6x4",
      "5532T 4x2",
      "5532T 6x4",
      "5532T HR",
    ],
    "Eicher Motors": [
      "Pro 6040",
      "Pro 6046",
      "Pro 6055XP",
      "Pro 6055XP 4x2",
      "Pro 8035XM",
      "Pro 8040XM",
      "Pro 8055",
    ],
    "Great Dane": ["Champion", "Everest", "Freedom"],
    Hyundai: ["HT Dry Van", "HT Flatbed", "HT Reefer"],
    Krone: ["Box Liner", "Cool Liner", "Profi Liner"],
    "Schmitz Cargobull": ["S.CS Universal", "S.KO Cool", "S.PR"],
    "Scania India": [
      "G 410 6x2",
      "G 410 6x4",
      "P 320 6x2",
      "P 320 6x4",
      "R 500 6x2",
      "R 500 6x4",
      "S 730 6x2",
      "S 730 6x4",
      "T 420 6x2",
      "T 420 6x4",
    ],
    "Tata Motors": [
      "Prima 5530.S",
      "Prima 5530.S LX",
      "Signa 4021.S",
      "Signa 4023.S",
      "Signa 4025.S",
      "Signa 4623.S",
      "Signa 4830.T",
      "Signa 4930.T",
      "Signa 5530.S",
      "Signa 5530.S BSVI-4x2",
      "Signa 5530.S",
    ],
    Utility: ["3000R", "4000D-X", "VS2RA"],
    Wabash: ["ArcticLite", "Dry Van", "DuraPlate"],
  },
  truck: {
    "Ashok Leyland": [
      "2820",
      "4X2 (GVW : 19T) HB",
      "6X2 (GVW : 26T - 31T) HB",
      "6X4 HB",
      "8X2 (GVW : 35T) HB",
      "10X2 (GVW : 48T) HB",
      "Bada Dost",
      "Boss 1115",
      "BOSS",
      "ecomet Star",
      "Ecomet 1015",
      "ICV Tippers",
      "Partner Super",
    ],
    BharatBenz: [
      "1617R",
      "2823C",
      "3123R",
      "4228R",
      "HDT C (19-35 tonnes)",
      "HDT R (28-48 tonnes)",
      "HDT RT (28-48 tonnes)",
      "HDT T (40-55 tonnes)",
      "MDT (10-19 tonnes)",
    ],
    Eicher: [
      "Pro 2049",
      "Pro 2049 CNG",
      "Pro 2049 EV",
      "Pro 2049 Plus",
      "Pro 2049XP",
      "Pro 2050",
      "Pro 2055",
      "Pro 2055 EV",
      "Pro 2055K",
      "Pro 2059 CNG",
      "Pro 2059 Plus",
      "Pro 2059XP",
      "Pro 2059XP CNG",
      "Pro 2075",
      "Pro 2075 CNG",
      "Pro 2080XP",
      "Pro 2090",
      "Pro 2095",
      "Pro 2095XP Plus",
      "Pro 2109 Turbo+ CNG",
      "Pro 2110 6S",
      "Pro 2110 7S",
      "Pro 2110 CNG",
      "Pro 2110XP",
      "Pro 2110XP Plus",
      "Pro 2110XP Plus CNG",
      "Pro 2114XP",
      "Pro 2114XP CNG",
      "Pro 2118",
      "Pro 2118XP Plus",
      "Pro 2119 CNG",
      "Pro 2119 Truck",
      "Pro 3012",
      "Pro 3014",
      "Pro 3015",
      "Pro 3015 L32",
      "Pro 3015 L32 CNG",
      "Pro 3015XP",
      "Pro 3018",
      "Pro 3018 CNG",
      "Pro 3018 Plus",
      "Pro 3018XP Plus",
      "Pro 3019",
      "Pro 3019 CNG",
      "Pro 6028",
      "Pro 6028 CNG",
      "Pro 6035",
      "Pro 6041",
      "Pro 6042",
      "Pro 6048",
      "Pro 6048XP",
      "Pro 8035XM",
      "Pro X",
    ],
    "Force Motors": [
      "Trax Delivery Van",
      "Traveller Delivery Van",
      "Traveller Delivery Van Wider Body",
      "Urbania",
    ],
    Freightliner: ["114SD", "122SD", "Cascadia", "M2 106"],
    Kenworth: ["T270", "T680", "T880", "W990"],
    Mack: ["Anthem", "Granite", "LR", "Pinnacle"],
    Mahindra: [
      "FURIO 10",
      "FURIO 11",
      "FURIO 12",
      "FURIO 14",
      "FURIO 14 HD",
      "FURIO 16",
      "FURIO 17",
      "FURIO 7",
      "Jayo",
      "Loadking Optimo",
    ],
    Peterbilt: ["389", "520", "567", "579"],
    "Scania India": [
      "G 500 6x4",
      "G310 6x2",
      "G410",
      "P360",
      "P410 6x2",
      "P410 8x4",
      "R500",
      "R500 V8 Puller",
      "R580 V8",
    ],
    "SML Isuzu": [
      "Prestige CNG",
      "Prestige Diesel",
      "Samrat GS",
      "Samrat GS CNG",
      "Samrat GS XT",
      "Samrat I2I2/I3I2 Diesel",
      "Sartaj 5252 CNG",
      "Sartaj 5252 Diesel",
      "Sartaj GS 59 CNG",
      "Sartaj GS 59 Diesel",
      "Sartaj HG 72 CNG",
      "Sartaj HG 72 Diesel",
      "Supreme GS",
      "Supreme Metro",
    ],
    "Tata Motors": [
      "710 LPT",
      "Ace",
      "LPT 1009G",
      "LPT 1012",
      "LPT 1109G",
      "LPT 1112",
      "LPT 1212",
      "LPT 1216",
      "LPT 1416",
      "LPT 1612G",
      "LPT 1616",
      "LPT 1816",
      "LPT 1916",
      "LPT 709G",
      "LPT 710",
      "LPT 712",
      "LPT 912",
      "LPT GOLD 710",
      "LPK 1416",
      "LPK 2821.K FE+ RMC",
      "Prima",
      "PRIMA 2830.K HRT",
      "PRIMA 2830.K REPTO",
      "PRIMA 2830.K SRT",
      "PRIMA 3530.K HRT",
      "PRIMA 3530.K SRT",
      "SFC 407 GOLD",
      "SFC 712",
      "SIGNA 1923.K",
      "SIGNA 2821.T",
      "SIGNA 2823.T",
      "SIGNA 2830.K 8 Cum REPTO RMC",
      "SIGNA 3125.T",
      "SIGNA 3525.T",
      "SIGNA 4021.S",
      "SIGNA 4025.S",
      "SIGNA 4225.T",
      "SIGNA 4623.S",
      "SIGNA 4830.T",
      "SIGNA 4930.T",
      "SIGNA 5530.S",
      "Signa",
      "Ultra",
      "ULTRA K.14",
      "ULTRA T.11",
      "ULTRA T.16",
      "ULTRA T.18",
      "ULTRA T.19",
      "ULTRA T.6",
      "ULTRA T.7",
      "ULTRA T.9",
    ],
    "Volvo Trucks India": [
      "FH 520",
      "FM 420",
      "FM 420 4x2",
      "FM 420 LNG 4x2 Tractor",
      "FMX 460",
      "FMX 460 8x4",
      "FMX 500 8x4",
      "FHL Electric",
      "FM 500 6x4 PULLER",
    ],
  },
};